package com.example.india11;

import androidx.fragment.app.Fragment;

import com.example.india11.Adapters.AvailableContestsAdapter;

public class Common {
    public static Fragment activeFragment;
    public static String userNameID = " ";
    public static String profileName = " ";
    public static String profileEmail = " ";
    public static String profileMobile = " ";
    public static String totalBalance = " ";
    public static String bonusBalance = " ";
    public static String winningBalance = " ";
    public static String accountNumber = " ";
    public static String accountHolder = " ";
    public static String accountBank = " ";
    public static String accountIfsc = " ";
    public static long addedMoney = 0;
    public static long previousTotalMoney = 0;
    public static long previousWinningAmount = 0;
    public static long withdrawAmountRequest = 0;
    public static String avlContestId = " ";
    public static String subContestId = " ";
    public static double creditUsed = 0.0;
    public static String isChecked = "No";
    public static long totalCredit;
    public static String teamCode;
    public static String teamOneName;
    public static String teamTwoName;
    public static String matchName;
    public static String contestsName;
    public static String contestsTime;
    public static String link;
    public static String teamOneLogo;
    public static String teamTwoLogo;
    public static String teamOneCount;
    public static String teamTwoCount;
    public static String previewType;
    public static String teamId;
    public static String firebaseId;
    public static long walletBalance = 0;
    public static long entryFee = 0;
    public static String time;

    public static int position;
    public static AvailableContestsAdapter.ViewHolder holder;
    public static int totalSpots;
    public static int teamName;
    public static int multipleTeamC;
    public static String buttonType;
    public static String creationId;
    public static Double obPoints;
    public static Integer rank;
    public static String amountRequest;
    public static String refId;
    public static String requestTime;
    public static String trasactionType;
    public static String captainPid;
    public static String viceCaptainPid;
    public static String totalWinners;
    public static String versionName;
    public static String contestType;
    public static long usableBonus;
    public static long walletBonus;
    public static Integer playedLeague;
    public static Double investedAmount;
    public static Double earnedAmount;
    public static Integer wonLeague;
    public static String connectionName;
    public static String connectionProfile;
    public static String connectionUid;
    public static String verificationCode;
    public static String email;
    public static String user;
    public static String tid;
    public static int totalSpot;
    public static String cCode;
    public static String vcCode;
    public static String creationType;
    public static String previousCap;
    public static String previousViceCap;
    public static String tossTime;
    public static String selectedTeam;
    public static String tossCId;
    public static Long tossPrize;
    public static Integer joined;
    public static Integer total;
    public static String groupId;
    public static String userProfilePic;
    public static String groupName;
    public static String groupPic;
    public static String groupCreation;
    public static String miPin;
    public static String pinType;
    public static String matchStatus;
    public static String nickName;
    public static String earned;
    public static String played;
    public static String won;
    public static String seriesName;
    public static String seriesId;
    public static String swTc;
    public static Double creditLeft;
    public static Integer wk;
    public static Integer bt;
    public static Integer br;
    public static Integer ar;
    public static Integer tOneC;
    public static Integer tTwoC;
    public static String tOne;
    public static String tTwo;
    public static String c;
    public static String vc;
    public static String oldCap;
    public static String oldVcap;
}
